-- #39: the permanent "this game has been accused" record. Generated by drizzle-kit from db/schema.ts, then made
-- idempotent by hand (IF NOT EXISTS; ENABLE ROW LEVEL SECURITY is a no-op when already on), so it is safe to apply
-- manually (Supabase SQL editor / connector) AND to have `npm run db:migrate` apply it again afterwards.
-- RLS on with NO policies: Supabase's Data API (anon / authenticated keys) can neither read nor write this table.
-- The server connects as the postgres role, which bypasses RLS.
CREATE TABLE IF NOT EXISTS "closed_games" (
	"game_id" text PRIMARY KEY NOT NULL,
	"case_id" text NOT NULL,
	"outcome" text NOT NULL,
	"accused_id" text,
	"closed_at" timestamp with time zone DEFAULT now(),
	CONSTRAINT "closed_games_outcome_check" CHECK ("closed_games"."outcome" in ('won', 'lost'))
);
--> statement-breakpoint
ALTER TABLE "closed_games" ENABLE ROW LEVEL SECURITY;
